name: Test Python Library

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
